# Generated by Django 4.2 on 2023-04-07 04:56

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("product", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="inbound",
            name="inbound_date",
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AddField(
            model_name="inbound",
            name="inbound_price",
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name="inbound",
            name="product",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="product.product",
            ),
        ),
        migrations.AddField(
            model_name="inbound",
            name="quantity",
            field=models.PositiveIntegerField(null=True),
        ),
    ]
