# Generated by Django 4.2 on 2023-04-07 06:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("product", "0002_inbound_inbound_date_inbound_inbound_price_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="outbound",
            name="outbound_date",
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name="outbound",
            name="outbound_price",
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name="outbound",
            name="product",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="product.product",
            ),
        ),
        migrations.AddField(
            model_name="outbound",
            name="quantity",
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name="inbound",
            name="inbound_date",
            field=models.DateField(null=True),
        ),
    ]
